### ISSUE TITLE
Translation language

### ISSUE THREAD

**Issue by szerzs-collab** [TheHudek/FandomVideoGenerator#2]
What other language besides English can be voiced?
How to make voice acting in Russian? Thanks

**Comment by TheHudek** [comment]
Hi,

Here's a list of available voices for Amazon's Polly: [Polly voices.](https://docs.aws.amazon.com/polly/latest/dg/voicelist.html)
In `voices.py` change `'Matthew'` to either `'Tatyana'` or `'Maxim'` and it should work.
